### ISSUE TITLE
Binary data

### ISSUE THREAD

**Issue by dev4fams** [hexlabsio/schema-api-ts#4]
How do you specify binary data in the schema?  Specifically, uploading binary data and response is binary data (ex: PDF or TIF)?

**Comment by chrisbarbour** [comment]
In the OpenApi Schema part you would define the path like this
```
'/pdf': {
      get: {
        operationId: 'getPdf',
        security: read,
        responses: {
          200: {description: 'Base64 encoded PDF file', content: {'application/octet-stream': {schema: SchemaBuilder.create().string()}}},
        }
      }
    }
```

Then you would respond using `Buffer.from(myPdf).toString('base64')`.

I don't think you can specify raw binary in open api
